version: 2
jobs:
  build:
    docker:
      - image: heroku/heroku:16
    working_directory: ~/webrtc-streamer
    
    steps:
      - checkout
      
      - setup_remote_docker: 
          docker_layer_caching: true

      - run:
          name: Install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region ap-southeast-1)
            
      - run: 
          name: "Build & Push Docker Image"
          command: |
            docker build --rm=false -t $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/rtsp2webrtcaws:latest .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/rtsp2webrtcaws:latest

