version: 1
machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

deployment:
  staging:
    branch: master
    commands:
        - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        - docker build --rm=false -t registry.heroku.com/rtsp2webrtcteleclaw/web .
        - docker push registry.heroku.com/rtsp2webrtcteleclaw/web:latest


